dist: trusty
sudo: required
language: bash

before_install:
  curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: H+T3CJWrs4Gg4wHhTHRYaq3cgEVwMA5K4zv2yQwsZjBbGrgGVOhoRhMEnv7IkhJ7X8BNJlXuLOxdOAj7hTIupJwB4e4uUaC8+kEtoExPGo5sASi/QaYKZNkz2frizcHQXj/c/gU/DO3R3Ki7fHYQrDTElTRb1rZIkBfLDWlD8LEcjJXeOYsn3ba6XNtNjlPrnYjpvVLH3jq798xiAv3FTp10/5hJby8eqrFdizMy/8riQGmfiOj02dqkWsvS6rvvochB7Ju06vOvS/t1XfKYIFp5OQQzsjA4NHjvDYpsvZALu4pbEHz/tJhZghgy3ox5L0Qjc5ei6icIRAG46D+HwXzI5HWHSIvUwg3sKWOwwlYEhU8x9RE5GZvioU+FXjgdYU6BKB71hlPPkk4tQtuft8omru9xvrcqzXI7nj2Qfx8MTRsPXjhK8FYqPcm3P9tMcIMCqn/rN2HPRT4eJG3P7Seco15ymA69jdK+Sm2l3kKhHrVxW9xWp7KiOMna7h6uXr1E9Z4D6RHdO4S7c9PfYZC+KY0wCat4xYhIAkGBDnzN2ZNz0nS2YVl/MDgxcM72+EgA+zamCh0G4pdRiEjM5lFSvBXEHElEo9ZOD5cnp+Flcze5pQvn+/W9cziZu+zd1zgajpWcoJcOOGXgL9a8gMqrMTo6qLRNzuy18RAsKHE=
