---
# tasks file for app
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Add unit file for Puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/appuser/db_config
    owner: root
    group: root

- name: enable puma
  systemd: name=puma enabled=yes

- name: Add Cassandra repository to sources
  apt_repository:
    repo: deb http://www.apache.org/dist/cassandra/debian 36x main
    filename: cassandra.sources.list
    state: present

- name: Update cache
  apt:
    update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install python-apt
  apt:
    name: python-apt
    state: latest
    update_cache: yes
